version: '3.9'
services:
  shop.product.postgres:
    image: postgres:14-alpine
    restart: always
    container_name: shop.product.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      -  shop.product:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      -  shop_net

  shop.product.pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: shop.product.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      -  shop.product.postgres
    networks:
      -  shop_net

volumes:
  shop.product:

networks:
  shop_net:
    driver: bridge
