# Create a new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "Aad4@nmail.ru",
  "name": "Alexey Ivanov",
  "password": "12345678"
}

###

# Get user by ID
GET http://localhost:3000/api/users/679639cbad541ce71b1e37f3 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Aad4@nmail.ru",
  "password": "12345678"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0N2ZjMzQ0NDRmYWM2MmE4MDVmYjgiLCJlbWFpbCI6IkFJQG5tYWlsLnJ1IiwibmFtZSI6IkFsZXhleSBJdmFub3YiLCJ0b2tlbklkIjoiZWYxN2U2ZGItY2MxYi00ZDBlLThiMzMtMzk2ODY0NTQ0NWViIiwiaWF0IjoxNzM3ODcwNjQ5LCJleHAiOjE3NDA0NjI2NDl9.lZMnHDaCqgmfWMzTn7RPE8_KMByJlNGJQW9ITyDuZPE
###

# Check user token
POST http://localhost:3000/api/users/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0N2ZjMzQ0NDRmYWM2MmE4MDVmYjgiLCJlbWFpbCI6IkFJQG5tYWlsLnJ1IiwibmFtZSI6IkFsZXhleSBJdmFub3YiLCJpYXQiOjE3Mzc5OTI0NjIsImV4cCI6MTczNzk5Mjc2Mn0.oKhgOIWYMJF11rJ5P6BOfrIT-r31s4xjxgYz7oX_x8k

###

# Update password
POST http://localhost:3000/api/users/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0N2ZjMzQ0NDRmYWM2MmE4MDVmYjgiLCJlbWFpbCI6IkFJQG5tYWlsLnJ1IiwibmFtZSI6IkFsZXhleSBJdmFub3YiLCJpYXQiOjE3Mzc4NzAxNDcsImV4cCI6MTczNzg3MDQ0N30.y0rsM7vlwhrwMgWJl158gf8oh5pH-Ve8HPoJtX864h8
Content-Type: application/json

{
  "oldPassword": "123sgrgfg1",
  "newPassword": "123sgrgfg2"
}

###

# Create a new product
POST http://localhost:3000/api/shop/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2I3NmFlNjUwOWUxZDc1ZGVmMjg5ODYiLCJlbWFpbCI6IkFhZDRAbm1haWwucnUiLCJuYW1lIjoiQWxleGV5IEl2YW5vdiIsImlhdCI6MTc0MDA3NjgyNSwiZXhwIjoxNzQwMDc3MTI1fQ.fMd_Xek80EDGnC1u_t187pYeu4vNlWLFqGeRUx6BwbI
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Fender Esquire yty try try try trytr ytry try try rty rty rty try trytryrtyr
--boundary
Content-Disposition: form-data; name="description"

Бюджетная модель, которую Брюс Спрингстин переделал под себя и усовершенствовал
--boundary
Content-Disposition: form-data; name="typeCode"

ukulele
--boundary
Content-Disposition: form-data; name="barcode"

0684-345rg eryre ytyt fgfyjf fjyj kut jtyjtr utrurty rty
--boundary
Content-Disposition: form-data; name="countStrings"

4
--boundary
Content-Disposition: form-data; name="price"

425.5
--boundary
Content-Disposition: form-data; name="photoFile"; filename="Фото-1.JPG"

< /home/oem/Загрузки/IMG_8728.JPG
--boundary--

###

# Get all products
GET http://localhost:3000/api/shop/products HTTP/1.1

###

# Get products with not correct filter

GET http://localhost:3000/api/shop/products?sortDirection=desc&sortBy=test&page=1 HTTP/1.1

###

# Get products with countStrings = [6,4]

GET http://localhost:3000/api/shop/products?sortDirection=desc&sortBy=createDate&page=1&countsStrings=6&countsStrings=4 HTTP/1.1

###

# Get products with typeCodes = electric

GET http://localhost:3000/api/shop/products?typeCodes=electric HTTP/1.1

###


# Get product by ID
GET http://localhost:3000/api/shop/products/0e4f25c4-7246-4206-9525-5174e35b757c HTTP/1.1

###

# Create a new product without photo
POST http://localhost:3000/api/shop/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2I3NmFlNjUwOWUxZDc1ZGVmMjg5ODYiLCJlbWFpbCI6IkFhZDRAbm1haWwucnUiLCJuYW1lIjoiQWxleGV5IEl2YW5vdiIsImlhdCI6MTc0MDA3ODY3MCwiZXhwIjoxNzQwMDc4OTcwfQ.6oNxuENXBDF4xWprfe-dXG7sinIKGb_86XqUWxs-yNA
Content-Type: application/json

{
  "name": "Fender Esquire",
  "description": "Бюджетная модель, которую Брюс Спрингстин переделал под себя и усовершенствовал",
  "photo": "2025/01/1246dd6d-8b8c-40a4-a128-bb5e20c44165.jpeg",
  "typeCode": "electric",
  "barcode": "50684-345",
  "countStrings": 6,
  "price": 145.5
}

###

# Delete the product by id
DELETE http://localhost:3000/api/shop/products/039f2542-d22a-4b8d-95c4-d22696f30817 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2I3NmFlNjUwOWUxZDc1ZGVmMjg5ODYiLCJlbWFpbCI6IkFhZDRAbm1haWwucnUiLCJuYW1lIjoiQWxleGV5IEl2YW5vdiIsImlhdCI6MTc0MDA3OTUwOCwiZXhwIjoxNzQwMDc5ODA4fQ.yJ6KCOFtpVZkxBimvbKkZBN6i8XIvPBRqrur1xEIg5I

###

# Update product by id
PUT http://localhost:3000/api/shop/products/7f4d1512-5350-48c8-a50d-8bb958a56914 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2I3NmFlNjUwOWUxZDc1ZGVmMjg5ODYiLCJlbWFpbCI6IkFhZDRAbm1haWwucnUiLCJuYW1lIjoiQWxleGV5IEl2YW5vdiIsImlhdCI6MTc0MDA3OTk1NSwiZXhwIjoxNzQwMDgwMjU1fQ.oGBZuGnGZUqjR90IDovwK93Vle1G7UbNBpLknXCWfbs
Content-Type: application/json

{
  "name": "Fender Esquire Измененное",
  "description": "Бюджетная модель, которую Брюс Спрингстин переделал под себя и усовершенствовал",
  "photo": "cgdgfgfgf",
  "typeCode": "acoustic",
  "barcode": "50684-345",
  "countStrings": 12,
  "price": 145.5
}


###
POST http://localhost:3000/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="Фото-1.JPG"

< /home/oem/Загрузки/IMG_8728.JPG
--boundary--

# Get file by ID
GET http://localhost:3000/api/files/67b783c1fc11eb7ec96f5b65 HTTP/1.1

###

